/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JLabel;
import profile.AddInfo;
import profile.BasicInfo;
import profile.CheckingAccInfo;
import profile.DLInfo;
import profile.MedicalRecords;
import profile.SavingAccInfo;

/**
 *
 * @author palak
 * MainJFrame from where create/view jPanels can be called to create and view profiles.
 */
public class CreateJFrame extends javax.swing.JFrame {

    //Reference Variables
    BasicInfo       basicInfo;
    AddInfo         addInfo;
    CheckingAccInfo checkingAccInfo;
    SavingAccInfo   savingAccInfo;
    DLInfo          dlInfo;
    MedicalRecords  medicalRecords;
    JLabel          dlImage;
    
    /** Creates new form CreateJFrame */
    private CreateJFrame() {
        
        initComponents();
        
        //Initializing new objets
        basicInfo       = new BasicInfo();
        addInfo         = new AddInfo();
        checkingAccInfo = new CheckingAccInfo();
        dlInfo          = new DLInfo();
        medicalRecords  = new MedicalRecords();
        savingAccInfo   = new SavingAccInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateSplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        txtBasicInfo = new javax.swing.JLabel();
        btnCreateBasic = new javax.swing.JButton();
        btnViewBasic = new javax.swing.JButton();
        txtAddress = new javax.swing.JLabel();
        btnCreateAdd = new javax.swing.JButton();
        btnViewAdd = new javax.swing.JButton();
        txtAccountInfo = new javax.swing.JLabel();
        btnCreateAcc = new javax.swing.JButton();
        btnViewAcc = new javax.swing.JButton();
        txtDLInfo = new javax.swing.JLabel();
        btnCreateDL = new javax.swing.JButton();
        btnViewDL = new javax.swing.JButton();
        txtMedical = new javax.swing.JLabel();
        btnCreateMedical = new javax.swing.JButton();
        btnViewMedical = new javax.swing.JButton();
        txtDLInfo1 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        InfoPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setBackground(new java.awt.Color(0, 153, 153));

        txtBasicInfo.setText("Basic Information");

        btnCreateBasic.setText("Create");
        btnCreateBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBasicActionPerformed(evt);
            }
        });

        btnViewBasic.setText("View");
        btnViewBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBasicActionPerformed(evt);
            }
        });

        txtAddress.setText("Address Information");

        btnCreateAdd.setText("Create");
        btnCreateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddActionPerformed(evt);
            }
        });

        btnViewAdd.setText("View");
        btnViewAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddActionPerformed(evt);
            }
        });

        txtAccountInfo.setText("Bank Information");

        btnCreateAcc.setText("Create");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        btnViewAcc.setText("View");
        btnViewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccActionPerformed(evt);
            }
        });

        txtDLInfo.setText("Driver's Liscense ");

        btnCreateDL.setText("Create");
        btnCreateDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDLActionPerformed(evt);
            }
        });

        btnViewDL.setText("View");
        btnViewDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDLActionPerformed(evt);
            }
        });

        txtMedical.setText("Medical Records");

        btnCreateMedical.setText("Create");
        btnCreateMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalActionPerformed(evt);
            }
        });

        btnViewMedical.setText("View");
        btnViewMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalActionPerformed(evt);
            }
        });

        txtDLInfo1.setText("Information");

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCreateDL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(btnViewDL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBasicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(txtMedical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDLInfo1)
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewBasic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateBasic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewAcc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateAcc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCreateMedical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(btnViewMedical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress)
                    .addComponent(txtDLInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBasicInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateBasic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBasic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAccountInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAcc)
                .addGap(18, 18, 18)
                .addComponent(txtDLInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDLInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateDL)
                .addGap(10, 10, 10)
                .addComponent(btnViewDL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateMedical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewMedical)
                .addGap(29, 29, 29)
                .addComponent(btnViewProfile)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        CreateSplitPane.setLeftComponent(ControlPanel);

        InfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        CreateSplitPane.setRightComponent(InfoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ViewProfileJPanel viewProfilePanel = new ViewProfileJPanel(basicInfo, addInfo, dlInfo, checkingAccInfo, savingAccInfo, medicalRecords, dlImage);
        CreateSplitPane.setRightComponent(viewProfilePanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnViewMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalActionPerformed
        // TODO add your handling code here:
        ViewMedicalJPanel viewMedPanel = new ViewMedicalJPanel(medicalRecords);
        CreateSplitPane.setRightComponent(viewMedPanel);
    }//GEN-LAST:event_btnViewMedicalActionPerformed

    private void btnCreateMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalActionPerformed
        // TODO add your handling code here:
        CreateMedicalJPanel createMedPanel = new CreateMedicalJPanel(medicalRecords);
        CreateSplitPane.setRightComponent(createMedPanel);
    }//GEN-LAST:event_btnCreateMedicalActionPerformed

    private void btnViewDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDLActionPerformed
        // TODO add your handling code here:
        ViewDLJPanel viewDLPanel = new ViewDLJPanel(dlInfo, dlImage);
        CreateSplitPane.setRightComponent(viewDLPanel);
    }//GEN-LAST:event_btnViewDLActionPerformed

    private void btnCreateDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDLActionPerformed
        // TODO add your handling code here:
        CreateDLJPanel createDLPanel = new CreateDLJPanel(dlInfo,dlImage);
        CreateSplitPane.setRightComponent(createDLPanel);
    }//GEN-LAST:event_btnCreateDLActionPerformed

    private void btnViewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccActionPerformed
        // TODO add your handling code here
        ViewBankJPanel viewBankPanel = new ViewBankJPanel(savingAccInfo, checkingAccInfo);
        CreateSplitPane.setRightComponent(viewBankPanel);
    }//GEN-LAST:event_btnViewAccActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // TODO add your handling code here:
        CreateBankJPanel createBankPanel = new CreateBankJPanel(savingAccInfo, checkingAccInfo);
        CreateSplitPane.setRightComponent(createBankPanel);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnViewAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddActionPerformed
        // TODO add your handling code here:
        ViewAddJPanel viewAddPanel = new ViewAddJPanel(addInfo);
        CreateSplitPane.setRightComponent(viewAddPanel);
    }//GEN-LAST:event_btnViewAddActionPerformed

    private void btnCreateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddActionPerformed
        // TODO add your handling code here:
        CreateAddJPanel createAddPanel = new CreateAddJPanel(addInfo);
        CreateSplitPane.setRightComponent(createAddPanel);
    }//GEN-LAST:event_btnCreateAddActionPerformed

    private void btnViewBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBasicActionPerformed
        // TODO add your handling code here:
        ViewBasicJPanel viewBasicPanel = new ViewBasicJPanel(basicInfo);
        CreateSplitPane.setRightComponent(viewBasicPanel);
    }//GEN-LAST:event_btnViewBasicActionPerformed

    private void btnCreateBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBasicActionPerformed
        // TODO add your handling code here:
        CreateBasicJPanel createBasicPanel = new CreateBasicJPanel(basicInfo);
        CreateSplitPane.setRightComponent(createBasicPanel);
    }//GEN-LAST:event_btnCreateBasicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JSplitPane CreateSplitPane;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnCreateAdd;
    private javax.swing.JButton btnCreateBasic;
    private javax.swing.JButton btnCreateDL;
    private javax.swing.JButton btnCreateMedical;
    private javax.swing.JButton btnViewAcc;
    private javax.swing.JButton btnViewAdd;
    private javax.swing.JButton btnViewBasic;
    private javax.swing.JButton btnViewDL;
    private javax.swing.JButton btnViewMedical;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel txtAccountInfo;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtBasicInfo;
    private javax.swing.JLabel txtDLInfo;
    private javax.swing.JLabel txtDLInfo1;
    private javax.swing.JLabel txtMedical;
    // End of variables declaration//GEN-END:variables

}
