/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JLabel;
import profile.AddInfo;
import profile.BasicInfo;
import profile.CheckingAccInfo;
import profile.DLInfo;
import profile.MedicalRecords;
import profile.SavingAccInfo;

/**
 *
 * @author palak
 * This ViewJPanel is the report panel to view the person profile information saved.
 */
public class ViewProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfileJPanel
     */
    
    //Reference variables
    BasicInfo basicInfo;
    AddInfo addInfo;
    DLInfo dlInfo;
    CheckingAccInfo checkingAccInfo;
    SavingAccInfo savingAccInfo;
    MedicalRecords medicalRecords;
    JLabel dlImage;
    
    public ViewProfileJPanel(BasicInfo basicInfo, AddInfo addInfo, DLInfo dlInfo, CheckingAccInfo checkingAccInfo, SavingAccInfo savingAccInfo, MedicalRecords medicalRecords, JLabel dlImage) {
        
        initComponents();
        
        //Initialize the variable
        this.basicInfo = basicInfo;
        this.addInfo = addInfo;
        this.dlInfo = dlInfo;
        this.checkingAccInfo = checkingAccInfo;
        this.savingAccInfo = savingAccInfo;
        this.dlImage = dlImage;
        this.medicalRecords = medicalRecords;
        
        displayProfileInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblPhoneNum = new javax.swing.JLabel();
        lblWSSN = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblStreetAdd = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        lblCheckingAccNum = new javax.swing.JLabel();
        lblSaving = new javax.swing.JLabel();
        txtSavingBankName = new javax.swing.JTextField();
        lblCheckingRoutingNum = new javax.swing.JLabel();
        lblSavingAccBalance = new javax.swing.JLabel();
        txtCheckingRoutingNum = new javax.swing.JTextField();
        txtSavingAccNum = new javax.swing.JTextField();
        txtCheckingAccBalance = new javax.swing.JTextField();
        lblCheckingBankName = new javax.swing.JLabel();
        txtCheckingBankName = new javax.swing.JTextField();
        lblSavingAccNum = new javax.swing.JLabel();
        txtSavingAccBalance = new javax.swing.JTextField();
        lblCheckingAccBalance = new javax.swing.JLabel();
        lblSavingRouteNum = new javax.swing.JLabel();
        txtCheckingAccNum = new javax.swing.JTextField();
        txtSavingRoutingNum = new javax.swing.JTextField();
        lblSavingBankName = new javax.swing.JLabel();
        lblSaving1 = new javax.swing.JLabel();
        lblSaving2 = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtExpDate = new javax.swing.JTextField();
        lblExpDate = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lbllicenseNum = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        lblSaving3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageLabelView = new javax.swing.JLabel();
        txtStreetAdd = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        lblAlergy2 = new javax.swing.JLabel();
        txtAlergy2 = new javax.swing.JTextField();
        lblAlergy1 = new javax.swing.JLabel();
        txtAlergy1 = new javax.swing.JTextField();
        txtRecordNum = new javax.swing.JTextField();
        lblRecordNum = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        lblSaving4 = new javax.swing.JLabel();
        lblSaving5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Profile Information");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        lblDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDob.setText("Date Of Birth:");

        lblHeight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHeight.setText("Height:");

        txtPhoneNum.setEditable(false);

        txtSSN.setEditable(false);

        txtAge.setEditable(false);

        lblPhoneNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhoneNum.setText("Phone Number:");

        lblWSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWSSN.setText("Social Security Number:");

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        txtWeight.setEditable(false);

        txtLastName.setEditable(false);

        lblWeight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWeight.setText("Weight:");

        txtFirstName.setEditable(false);

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAge.setText("Age:");

        txtHeight.setEditable(false);

        txtDob.setEditable(false);

        lblState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblState.setText("State:");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCity.setText("City:");

        txtCity.setEditable(false);

        lblStreetAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStreetAdd.setText("Street Address:");

        txtZipCode.setEditable(false);

        txtState.setEditable(false);

        lblZipCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblZipCode.setText("Zip Code:");

        lblCheckingAccNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCheckingAccNum.setText("Account Number:");

        lblSaving.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving.setText("Account Type: Saving");

        txtSavingBankName.setEditable(false);

        lblCheckingRoutingNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCheckingRoutingNum.setText("Routing Number:");

        lblSavingAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSavingAccBalance.setText("Account Balance:");

        txtCheckingRoutingNum.setEditable(false);
        txtCheckingRoutingNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckingRoutingNumActionPerformed(evt);
            }
        });

        txtSavingAccNum.setEditable(false);

        txtCheckingAccBalance.setEditable(false);

        lblCheckingBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCheckingBankName.setText("Bank Name:");

        txtCheckingBankName.setEditable(false);

        lblSavingAccNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSavingAccNum.setText("Account Number:");

        txtSavingAccBalance.setEditable(false);

        lblCheckingAccBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCheckingAccBalance.setText("Account Balance:");

        lblSavingRouteNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSavingRouteNum.setText("Routing Number:");

        txtCheckingAccNum.setEditable(false);

        txtSavingRoutingNum.setEditable(false);

        lblSavingBankName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSavingBankName.setText("Bank Name:");

        lblSaving1.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving1.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving1.setText("Account Type: Checking");

        lblSaving2.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving2.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving2.setText("Address Information");

        lblBloodType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBloodType.setText("Blood Type:");

        txtExpDate.setEditable(false);
        txtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpDateActionPerformed(evt);
            }
        });

        lblExpDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExpDate.setText("Date Of Expiration:");

        txtIssueDate.setEditable(false);

        lblIssueDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIssueDate.setText("Date Of Issue:");

        txtLicenseNum.setEditable(false);

        lbllicenseNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllicenseNum.setText("License Number:");

        txtBloodType.setEditable(false);
        txtBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodTypeActionPerformed(evt);
            }
        });

        lblSaving3.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving3.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving3.setText("Medical Information");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Driving License:");

        imageLabelView.setBackground(new java.awt.Color(204, 204, 204));
        imageLabelView.setAutoscrolls(true);
        imageLabelView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtStreetAdd.setEditable(false);

        txtAlergy3.setEditable(false);

        lblAlergy2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlergy2.setText("Alergy 2:");

        txtAlergy2.setEditable(false);

        lblAlergy1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlergy1.setText("Alergy 1:");

        txtAlergy1.setEditable(false);

        txtRecordNum.setEditable(false);

        lblRecordNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRecordNum.setText("Medical Record Number:");

        lblAlergy3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlergy3.setText("Alergy 3:");

        lblSaving4.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving4.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving4.setText("Driver’s license Information");

        lblSaving5.setBackground(new java.awt.Color(0, 153, 153));
        lblSaving5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaving5.setForeground(new java.awt.Color(0, 153, 153));
        lblSaving5.setText("Basic Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(lblDob))
                                .addComponent(lblPhoneNum, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSaving5)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblWSSN)
                                .addGap(18, 18, 18)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblStreetAdd)
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblCity)
                                                    .addComponent(lblState))
                                                .addGap(30, 30, 30)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSaving2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtStreetAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblWeight)
                                                    .addComponent(lblHeight)
                                                    .addComponent(lblAge))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblZipCode)
                                                .addGap(30, 30, 30)
                                                .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(2, 2, 2)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblIssueDate)
                                .addComponent(lblExpDate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblBloodType))
                            .addComponent(lbllicenseNum, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaving4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblSaving3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblRecordNum)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAlergy3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAlergy2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAlergy2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAlergy1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCheckingAccNum)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCheckingAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(lblCheckingAccBalance)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCheckingAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCheckingRoutingNum)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCheckingRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(lblCheckingBankName))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSaving1)
                                            .addComponent(txtCheckingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imageLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSavingAccBalance)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSavingAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSavingAccNum)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSavingAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSavingBankName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSavingRouteNum, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSaving)
                                            .addComponent(txtSavingBankName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(txtSavingRoutingNum))))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWSSN)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhoneNum))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDob)
                                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbllicenseNum)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIssueDate))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblExpDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBloodType)))
                            .addComponent(imageLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSaving4)
                        .addComponent(lblSaving5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaving3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecordNum)
                            .addComponent(txtRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlergy1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlergy2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlergy3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaving1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCheckingBankName)
                            .addComponent(txtCheckingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCheckingRoutingNum)
                            .addComponent(txtCheckingRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCheckingAccNum)
                            .addComponent(txtCheckingAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCheckingAccBalance)
                            .addComponent(txtCheckingAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSaving)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavingBankName)
                            .addComponent(txtSavingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavingRouteNum)
                            .addComponent(txtSavingRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavingAccNum)
                            .addComponent(txtSavingAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavingAccBalance)
                            .addComponent(txtSavingAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(lblSaving2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStreetAdd)
                                .addGap(18, 18, 18)
                                .addComponent(lblCity)
                                .addGap(26, 26, 26)
                                .addComponent(lblState))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCheckingRoutingNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckingRoutingNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckingRoutingNumActionPerformed

    private void txtExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpDateActionPerformed

    private void txtBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodTypeActionPerformed

    private void displayProfileInfo() {
        //Basic Information
        txtFirstName.setText(basicInfo.getFirstName());
        txtLastName.setText(basicInfo.getLastName());
        txtSSN.setText(basicInfo.getSsn());
        txtDob.setText(basicInfo.getDateOfBirth());
        txtPhoneNum.setText(basicInfo.getPhoneNumber());
        txtAge.setText(basicInfo.getAge());
        txtWeight.setText(basicInfo.getWeight());
        txtHeight.setText(basicInfo.getHeight());
        
        //Address Information
        txtStreetAdd.setText(addInfo.getStreetAddress());
        txtCity.setText(addInfo.getCity());
        txtState.setText(addInfo.getState());
        txtZipCode.setText(addInfo.getZipCode());
        
        //Saving Account Information
        txtSavingBankName.setText(savingAccInfo.getBankName());
        txtSavingRoutingNum.setText(savingAccInfo.getBankRoutingNum());
        txtSavingAccNum.setText(savingAccInfo.getBankAccNum());
        txtSavingAccBalance.setText(savingAccInfo.getAccBalance());
        
        //Checking Account Information
        txtCheckingBankName.setText(checkingAccInfo.getBankName());
        txtCheckingRoutingNum.setText(checkingAccInfo.getBankRoutingNum());
        txtCheckingAccNum.setText(checkingAccInfo.getBankAccNum());
        txtCheckingAccBalance.setText(checkingAccInfo.getAccBalance());
        
        //DL Information
        txtLicenseNum.setText(dlInfo.getLicenseNum());
        txtIssueDate.setText(dlInfo.getIssueDate());
        txtExpDate.setText(dlInfo.getExpDate());
        txtBloodType.setText(dlInfo.getBloodType());
        dlImage = dlInfo.getDlImage();
        if(dlImage !=null){
        imageLabelView.setIcon(dlImage.getIcon());
        }
        
        //Medical Information
        txtRecordNum.setText(medicalRecords.getMedicalRecordNum());
        txtAlergy1.setText(medicalRecords.getAlergy1());
        txtAlergy2.setText(medicalRecords.getAlergy2());
        txtAlergy3.setText(medicalRecords.getAlergy3());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabelView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCheckingAccBalance;
    private javax.swing.JLabel lblCheckingAccNum;
    private javax.swing.JLabel lblCheckingBankName;
    private javax.swing.JLabel lblCheckingRoutingNum;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblRecordNum;
    private javax.swing.JLabel lblSaving;
    private javax.swing.JLabel lblSaving1;
    private javax.swing.JLabel lblSaving2;
    private javax.swing.JLabel lblSaving3;
    private javax.swing.JLabel lblSaving4;
    private javax.swing.JLabel lblSaving5;
    private javax.swing.JLabel lblSavingAccBalance;
    private javax.swing.JLabel lblSavingAccNum;
    private javax.swing.JLabel lblSavingBankName;
    private javax.swing.JLabel lblSavingRouteNum;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWSSN;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lbllicenseNum;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCheckingAccBalance;
    private javax.swing.JTextField txtCheckingAccNum;
    private javax.swing.JTextField txtCheckingBankName;
    private javax.swing.JTextField txtCheckingRoutingNum;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtRecordNum;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSavingAccBalance;
    private javax.swing.JTextField txtSavingAccNum;
    private javax.swing.JTextField txtSavingBankName;
    private javax.swing.JTextField txtSavingRoutingNum;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAdd;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
