

package userinterface.CustomerRole;


import Business.Customer.Customer;
import userinterface.RestaurantAdminRole.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    UserAccount user;
    Restaurant rest;
    EcoSystem system;
    Customer customer;
    /** Creates new form AdminWorkAreaJPanel */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount user, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.system = system;
        //System.out.println(system.getCustomerDirectory().getCustomerList().size());
        for(Customer c : system.getCustomerDirectory().getCustomerList() )
        {
            
                if(c.getName() == null ? user.getEmployee().getName() == null : c.getName().equals(user.getEmployee().getName()))
                {
                    this.customer = c;
                }
           
        }
        
        //System.out.println(this.customer.getName());
        txtName.setText(this.customer.getName());
        txtAddress.setText(this.customer.getAddress());
        txtPhone.setText(this.customer.getPhone());
        valueLabel.setText(this.customer.getName());
        jComboRestaurants.addItem("");
        for(Restaurant r : system.getRestaurantDirectory().getRestaurantList())
        {
            jComboRestaurants.addItem(r.getName());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboRestaurants = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Work Area - Customer Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Welcome! ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 290, 30));

        jLabel2.setText("Where would you like to eat today?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        jLabel3.setText("Phone:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 110, -1));

        txtName.setEditable(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 150, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 150, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel4.setText("Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 20));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 150, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, -1));

        jComboRestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRestaurantsActionPerformed(evt);
            }
        });
        add(jComboRestaurants, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 190, 170, -1));

        jLabel6.setText("Update Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jButton1.setText("Review Orders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if((txtAddress.getText() == "") || (txtPhone.getText() == ""))
        {
            JOptionPane.showMessageDialog(null,"Please fill all values!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else 
        {
            customer.setAddress(txtAddress.getText());
            customer.setPhone(txtPhone.getText());
        }       
        valueLabel.setText(rest.getName());
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jComboRestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRestaurantsActionPerformed
        // TODO add your handling code here:
        if(jComboRestaurants.getSelectedItem() != "")
        {
            String res = jComboRestaurants.getSelectedItem().toString();
            rest = system.getRestaurantDirectory().findRestaurant(res);
            CustomerPlaceOrder cpo = new CustomerPlaceOrder(userProcessContainer, customer, rest);
            userProcessContainer.add("CustomerOrder", cpo);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jComboRestaurantsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustomerMessageJPanel lcj = new CustomerMessageJPanel(userProcessContainer, user, system);
        userProcessContainer.add("CustomerOrder", lcj);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboRestaurants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
